### PR TITLE
resolvePackageSync: fixed infinite loop

### LINKED ISSUE #27: infinite loop if dependency is not exist
`resolveConfigSync` goes to inf loop (base eq `/`, and `resolve("/..")` eq `/`) if package not exist

### PR DESCRIPTION
**Pull request by zxqfox**
Fixes #27 

Ref #28

### CODE REVIEW

**Comment by creationix** [comment]
Looks good.

**Comment by zxqfox** [comment]
@creationix ;-) So?

**Comment by zxqfox** [comment]
Guys, can you merge this, please?

/cc @fjakobs @cadorn

**Comment by cadorn** [comment]
me no have access no more

**Comment by fjakobs** [comment]
thanks for fixing this!

**Pull request merged**
